### ISSUE TITLE
Typo: namespace reference

### ISSUE THREAD

**Issue by rginnow** [rcerljenko/laravel-paseto#1]
https://github.com/rcerljenko/laravel-paseto/blob/55f0303c04805e9f29d94c04c047516793ae56f4/src/Traits/HasPaseto.php#L3

Hey man, looks like just a simple copy/paste mistake maybe, but you used the namespace of LaravelJwt for your trait while everything else seems to be LaravelPaseto.

Other than that, code looks clean!

**Comment by rcerljenko** [comment]
Thanks! Fixed just now => https://github.com/rcerljenko/laravel-paseto/releases/tag/1.1.0
